mutation generate_login_challenge($address: String!){
  generate_login_challenge(req:{
    address: $address
  }){
    message
  }
}

{
  "address": "5Dnk6vQhAVDY9ysZr8jrqWJENDWYHaF3zorFA4dr9Mtbei77"
}

{
  "address": "5HT1nugEKpbnszsucUbZjMVXWm2AZGAetSYU13kHseWavCcq"
}


mutation login($address: String!, $signature: String!){
  login(req:{
    address: $address,
    signature: $signature
  }){
    refresh_token
    token	
    user{
      address
      id
      publicKey
      privateInfo{
        privateKey
      }
    }
  }
}

{
  "address":"5Dnk6vQhAVDY9ysZr8jrqWJENDWYHaF3zorFA4dr9Mtbei77",
  "signature":"0x5a1aa596fd20d5eddfd21fb4be11858a674bfda4f4fe7a7727137ca6b49387240c60268daba124723b2e71b83cabc4844b709c71b204433a94ecac2b96112e88"
}

{
  "address":"5HT1nugEKpbnszsucUbZjMVXWm2AZGAetSYU13kHseWavCcq",
  "signature":"0x7ed3100c4d3e66a90e07adb78e115f784ab1c1c9a01ac12507c0b9ff4cd6483ed09c887feab9384dbf32c70cee6e814989b01cb3d330a256f1c8d9f4ca32a782"
}



mutation upsert_owned_data($id: Int, $name: String!, $description: String!, $cid: String!, $type: String!, $iv: String!, $mac: String! ){
  upsert_owned_data(req:{
    id: $id,
    name: $name,
    description: $description,
    cid: $cid,
    type: $type,
    iv: $iv,
    mac: $mac
  }){
    id
    name
    description
    cid
    type
    iv
    mac
    started_at
    ended_at
    is_deleted
  }
}

{
  "id": null,
  "name": "name gql3",
  "description": "desc gql3",
  "cid": "cidcidcidcidcidcidcidcidcidcidcidcid gql3",
  "type": "type gql1"
}


mutation update_owned_data_metadata($id: Int!, $name: String!, $description: String!){
  update_owned_data_metadata(req:{
    id: $id,
    name:$name,
    description: $description
  }){
    affected_rows
  }
}

{
  "id": 29,
  "name": "name gql5",
  "description": "desc gql5"
}


mutation soft_delete_owned_data($id: Int!){
  soft_delete_owned_data(req:{
    id: $id
  }){
    affected_rows
  }
}

{
  "id": 26
}

mutation share($toUserId: uuid!, $originalOwnedDataId: Int!, $cid: String!, $iv: String!, $mac: String! ){
  share(req:{
    to_user_id: $toUserId,
    original_owned_data_id:$originalOwnedDataId,
    cid: $cid,
    iv: $iv,
    mac: $mac
  }){
    id
    from_user{
      id
      address
    }
    to_user{
      id
      address
    }
    name
    description
    cid
    shared_at
    original_owned_data{
      id
      type
    }
    iv
    mac
  }
}

{
  "toUserId": "41baaac1-8d35-42da-91ab-02efd424d71f",
  "originalOwnedDataId": 25,
  "cid": "cidcidcidcidcidcidcidcidcidcidcidcid gql4"
}


mutation update_shared_data_metadata($id: Int!, $name: String!, $description: String!){
  update_shared_data_metadata(req:{
    id: $id,
    name:$name,
    description: $description
  }){
    affected_rows
  }
}

{
  "id": 19,
  "name": "name gql4",
  "description": "desc gql4"
}


mutation delete_shared_data($id: Int!){
  delete_shared_data_by_pk(id:$id){
    id
  }
}

{
  "id": 19
}


mutation add_member($groupId: uuid!, $userId: uuid!, $roleId: Int!){
  insert_group_user(objects:[
    {
      group_id: $groupId,
      user_id: $userId,
      role_id: $roleId
    }
  ]){
    affected_rows
  }
}

{
  "groupId": "551030f9-6054-4ffa-b02d-a275398ec50d",
  "userId": "9c960778-6756-4fcb-b151-b1c84d34fbaa",
  "roleId": 1
}


mutation update_member($groupId: uuid!, $userId: uuid!, $roleId: Int!) {
  update_group_user_by_pk(
    pk_columns:{
      group_id: $groupId,
      user_id: $userId
    },
    _set: {
      role_id: $roleId
    }){
    group_id
    user_id
    role_id
  }
}

{
  "groupId": "551030f9-6054-4ffa-b02d-a275398ec50d",
  "userId": "9c960778-6756-4fcb-b151-b1c84d34fbaa",
  "roleId": 1
}


mutation delete_member($groupId: uuid!, $userId: uuid!) {
  delete_group_user_by_pk(group_id: $groupId, user_id: $userId){
    group_id
    user_id
    role_id
  }
}

{
  "groupId": "551030f9-6054-4ffa-b02d-a275398ec50d",
  "userId": "9c960778-6756-4fcb-b151-b1c84d34fbaa"
}


mutation create_doc($cid: String!, $ownerActorId: uuid!, $name: String!, $description: String!, $toActorId: uuid) {
  insert_document_one(object: {
    cid: $cid,
    owner_actor_id: $ownerActorId,
    to_actor_id: $toActorId,
    name: $name,
    description: $description
  }){
    cid
  }
}

{
  "cid": "cid9",
  "ownerActorId": "d0b2aaac-aad7-4320-b42c-7cc5f3d72df7",
  "toActorId": "3e4d4c1e-c0b1-433f-be0a-56cb662ce284",
  "name": "doc1",
  "description": "document 1"
}


query docs{
  document{
    cid
    owner_actor_id
    to_actor_id
    name
    description
    created_at
    owner{
      name
      address
      public_key
    }
    to_actor{
      name
      address
      public_key
    }
  }
}


query doc_by_cid($cid: String!){
  document_by_pk(cid: $cid){
    cid
    ownerActorId: owner_actor_id
    toActorId: to_actor_id
    name
    description
    createdAt: created_at
    owner{
      name
      address
      publicKey: public_key
    }
    to_actor{
      name
      address
      publicKey: public_key
    }
  }
}

{
  "cid": "cid1"
}

mutation update_doc($cid: String!, $name: String!, $description: String!) {
  update_document_by_pk(pk_columns:{
    cid: $cid
  },
  _set:{
    name: $name,
    description: $description
  }){
    cid
  }
}


{
  "cid": "cid2",
  "name": "doc7",
  "description": "document 2"
}


query get_security_data($actorId: uuid!) {
  actor_by_pk(id: $actorId){
    id
    name
    address
    publicKey: public_key
    privateInfo: private_info{
    	privateKey: security_data
  	}
  }
}

{
  "actorId": "d0b2aaac-aad7-4320-b42c-7cc5f3d72df7"
}

mutation create_group($name: String!, $publicKey: String!, $securityData: String!) {
  create_group(req: 
    {
      name: $name,
      public_key: $publicKey,
      security_data: $securityData
    }
  ){
    id
  }
}

{
  "name": "group30",
  "publicKey": "pubKey30",
  "securityData": "privKey30"
}

mutation upsert_member($groupId: uuid!, $userId: uuid!, $roleId: Int!){
  insert_group_user(objects:[
    {
      group_id: $groupId,
      user_id: $userId,
      role_id: $roleId
    }
  ],
    on_conflict:{
      constraint:group_user_pkey,
      update_columns:[role_id]
    }){
    affected_rows
  }
}

{
  "groupId": "03bae3e7-2a99-441a-97c4-2585954d588e",
  "userId": "9c960778-6756-4fcb-b151-b1c84d34fbaa",
  "roleId": 2
}


query find_full_actors($ids: [uuid!]!, $userId: uuid!) {
  actor(where:{
    _and:{
    	id:{_in:$ids}
      _or:[
        {
           id: {
        	  _eq:$userId
          }
      	},
        {
          users:{
            user_id:{
              _eq:$userId
            }
          }
        }
      ]
    }
  }){
    id
    name
    address
    publicKey: public_key,
    privateKey: security_data
  }
}


{
  "ids": [
    "d0b2aaac-aad7-4320-b42c-7cc5f3d72df7",
    "551030f9-6054-4ffa-b02d-a275398ec50d",
    "9c960778-6756-4fcb-b151-b1c84d34fbaa",
    "e43c5a55-46a7-41fb-ae64-b04480d8ab74",
    "c3bd2937-2cc0-4ba5-96c5-f4b7789c69cc"
  ],
  "userId": "e43c5a55-46a7-41fb-ae64-b04480d8ab74"
}

query find_full_actors($actorIds: [uuid!]!) {
  find_full_actors(req: {
    actorIds: $actorIds
  }){
    id
    address
    name
    publicKey
    privateKey
  }
}

{
  "actorIds": [
    "d0b2aaac-aad7-4320-b42c-7cc5f3d72df7",
    "551030f9-6054-4ffa-b02d-a275398ec50d",
    "9c960778-6756-4fcb-b151-b1c84d34fbaa",
    "e43c5a55-46a7-41fb-ae64-b04480d8ab74",
    "c3bd2937-2cc0-4ba5-96c5-f4b7789c69cc"
  ]
}

mutation delete_doc ($cid: String!) {
  delete_document_by_pk(cid: $cid){
    cid
  }
}

{
  "cid": "cid9"
}


query find_actor_by_id($actorId: uuid!) {
  actor_by_pk(id: $actorId){
    id
    name
    address
    publicKey: public_key
  }
}

{
  "actorId": "d0b2aaac-aad7-4320-b42c-7cc5f3d72df7"
}

query find_actor_by_address($address: String!) {
  actor(where:{
    address:{
      _eq: $address
    }
  }){
    id
    name
    address
    publicKey: public_key
  }
}

{
  "address": "5Dnk6vQhAVDY9ysZr8jrqWJENDWYHaF3zorFA4dr9Mtbei77"
}


query find_group_by_id($groupId: uuid!) {
  actor_by_pk(id: $groupId){
    id
    name
    publicKey: public_key,
    users {
      user {
        id
        address
        publicKey: public_key
      }
    }
  }
}


{
  "groupId": "551030f9-6054-4ffa-b02d-a275398ec50d"
}
