'use strict'

const {
  listPublicKeysSchema
} = require('./schemas')

/**
 * Provides endpoints related to JSON Web Keys
 */
module.exports = async function (fastify, opts) {
  fastify.register(async function (fastify) {
    /**
     * List the JSON Web public keys to enable other services to verify the
     * JWT tokens generated by the server
     */
    fastify.get('/list', { schema: listPublicKeysSchema }, listHandler)
  })
}

module.exports[Symbol.for('plugin-meta')] = {
  decorators: {
    fastify: [
      'jwt'
    ]
  }
}

function listHandler (req, reply) {
  return {
    keys: this.jwt.getPublicKeys()
  }
}
