-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE VIEW "public"."actor_private" AS
-- SELECT
--   "actor".id AS actor_id,
--   "actor".security_data
-- FROM
--   "actor";
